Repository GDSC-CEC/HacktoberFest-2022-Web-Development, pull requests merged in 2022-10, with the labels that each got.

#9 Updated the Table.
  Easy/table/table.html
Labels: hacktoberfest-accepted, hacktoberfest

#20 Updated the JavaScript function to alert.
  Easy/alert/alert.html
Labels: hacktoberfest-accepted, hacktoberfest

#25 Added drum project
  Projects/Drum Kit/.DS_Store
  Projects/Drum Kit/README.md
  Projects/Drum Kit/images/background-img.webp
  Projects/Drum Kit/images/crash.png
  Projects/Drum Kit/images/kick.png
  Projects/Drum Kit/images/snare.png
  Projects/Drum Kit/images/tom1.png
  Projects/Drum Kit/images/tom2.png
  Projects/Drum Kit/images/tom3.png
  Projects/Drum Kit/images/tom4.png
  Projects/Drum Kit/index.html
  Projects/Drum Kit/index.js
  Projects/Drum Kit/sounds/crash.mp3
  Projects/Drum Kit/sounds/kick-bass.mp3
  Projects/Drum Kit/sounds/snare.mp3
  Projects/Drum Kit/sounds/tom-1.mp3
  Projects/Drum Kit/sounds/tom-2.mp3
  Projects/Drum Kit/sounds/tom-3.mp3
  Projects/Drum Kit/sounds/tom-4.mp3
  Projects/Drum Kit/styles.css
Labels: hacktoberfest-accepted

#14 Update countVowels.html
  Hard/vowelsCount/countVowels.html
Labels: hacktoberfest-accepted

#17 vanithaak -- made a color guessing game
  .vscode/settings.json
  Projects/RGB colour Game/index.html
  Projects/RGB colour Game/index.js
  Projects/RGB colour Game/styles.css
Labels: Request_changes

#24 Name : Anurag Chakraborty LinkedIn : https://www.linkedin.com/in/anurag-chakraborty-841827174/ "Added the youtube link embedder , edited 1 file "
  Easy/addYoutube/addYoutube.html
  Easy/align/align.html
Labels: Request_changes

#38 Update random.html
  Medium/random/random.html
Labels: hacktoberfest-accepted

#41 Basic Calculator Project
  Projects/Basic Calculator/.config/configstore/update-notifier-npm.json
  Projects/Basic Calculator/index.html
  Projects/Basic Calculator/script.js
  Projects/Basic Calculator/style.css
  Projects/Basic Calculator/utils.css
Labels: hacktoberfest-accepted

#40 Name : Abhishek Kumar LinkedIn: www.linkedin.com/in/abhishek-kumar-264824208 "updated the date.html file"
  Medium/dateTime/date.html
Labels: Already-merged
